// Generated by gencpp from file markerlocator/markerpose.msg
// DO NOT EDIT!


#ifndef MARKERLOCATOR_MESSAGE_MARKERPOSE_H
#define MARKERLOCATOR_MESSAGE_MARKERPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace markerlocator
{
template <class ContainerAllocator>
struct markerpose_
{
  typedef markerpose_<ContainerAllocator> Type;

  markerpose_()
    : header()
    , order(0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)
    , quality(0.0)
    , timestamp()  {
    }
  markerpose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , order(0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)
    , quality(0.0)
    , timestamp()  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _order_type;
  _order_type order;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;

   typedef double _quality_type;
  _quality_type quality;

   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::markerlocator::markerpose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::markerlocator::markerpose_<ContainerAllocator> const> ConstPtr;

}; // struct markerpose_

typedef ::markerlocator::markerpose_<std::allocator<void> > markerpose;

typedef boost::shared_ptr< ::markerlocator::markerpose > markerposePtr;
typedef boost::shared_ptr< ::markerlocator::markerpose const> markerposeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::markerlocator::markerpose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::markerlocator::markerpose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::markerlocator::markerpose_<ContainerAllocator1> & lhs, const ::markerlocator::markerpose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.order == rhs.order &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta &&
    lhs.quality == rhs.quality &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::markerlocator::markerpose_<ContainerAllocator1> & lhs, const ::markerlocator::markerpose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace markerlocator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::markerlocator::markerpose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::markerlocator::markerpose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::markerlocator::markerpose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::markerlocator::markerpose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::markerlocator::markerpose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::markerlocator::markerpose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::markerlocator::markerpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b1f0f0642695a793c93c4a2dcaa8c41";
  }

  static const char* value(const ::markerlocator::markerpose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b1f0f0642695a79ULL;
  static const uint64_t static_value2 = 0x3c93c4a2dcaa8c41ULL;
};

template<class ContainerAllocator>
struct DataType< ::markerlocator::markerpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "markerlocator/markerpose";
  }

  static const char* value(const ::markerlocator::markerpose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::markerlocator::markerpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header 	 header\n"
"uint8    order\n"
"float64  x\n"
"float64  y\n"
"float64  theta\n"
"float64  quality\n"
"time     timestamp\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::markerlocator::markerpose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::markerlocator::markerpose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.order);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.quality);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct markerpose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::markerlocator::markerpose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::markerlocator::markerpose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "order: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.order);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "quality: ";
    Printer<double>::stream(s, indent + "  ", v.quality);
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARKERLOCATOR_MESSAGE_MARKERPOSE_H
